-- return {
--   "Pocco81/auto-save.nvim",
--   config = function()
--     require("auto-save").setup({
--       debounce_delay = 1000,
--       trigger_events = { "InsertLeave", "TextChanged" },
--       condition = function(buf)
--         if vim.fn.getbufvar(buf, "&buftype") ~= "" then return false end
--         return true
--       end,
--     })
--   end,
-- }
return {}
